enum CharacterActionTypes {
  GET_CHARACTERS_LIST_START = 'GET_CHARACTERS_LIST_START',
  GET_CHARACTERS_LIST_SUCCESS = 'GET_CHARACTERS_LIST_SUCCESS',
  GET_CHARACTERS_LIST_FAILURE = 'GET_CHARACTERS_LIST_FAILURE'
}
export default CharacterActionTypes;